---
galaxy_info:
  author: Gerasimov Anton
  description: Apache web server role with system information page
  company: Netology
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - web
    - apache
    - system-info

dependencies: []
