---
- name: Install Apache web server
  package:
    name: "{{ apache_package }}"
    state: present

- name: Create web content directory
  file:
    path: "{{ web_content_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure index.html with system information
  template:
    src: index.html.j2
    dest: "{{ web_content_dir }}/index.html"
    owner: root
    group: root
    mode: '0644'
  notify: restart apache

- name: Ensure Apache is started and enabled
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Configure firewall to allow HTTP traffic
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"

- name: Configure UFW to allow HTTP traffic
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Verify website accessibility
  uri:
    url: "http://{{ ansible_default_ipv4.address }}/"
    status_code: 200
    timeout: 30
  register: website_test
  until: website_test.status == 200
  retries: 3
  delay: 10
  ignore_errors: yes

- name: Display website status
  debug:
    msg: "Website is accessible at http://{{ ansible_default_ipv4.address }}/"
  when: website_test.status == 200
