---
apache_package: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
apache_service: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
web_content_dir: "{{ '/var/www/html' if ansible_os_family == 'RedHat' else '/var/www/html' }}"
